// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuilaeeozqfzzxfkcujp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aWxhZWVvenFmenp4ZmtjdWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDc1NzIsImV4cCI6MjA3MjMyMzU3Mn0.ghWSzO2oqZcxV0xJEmCE93ZuTT54vIzp1P3OtvUAFBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});